#- import_tasks: base_packages.yml
#- import_tasks: val_base.yml
#- import_tasks: ufwrules.yml
#- import_tasks: val_ufwrules.yml
#- import_tasks: ssh.yml
#- import_tasks: val_ssh.yml
#- import_tasks: fail2ban.yml
#- import_tasks: val_fail2ban.yml
#- import_tasks: chrony.yml
#- import_tasks: val_chrony.yml
#- import_tasks: cockpit.yml
#- import_tasks: val_cockpit.yml
#- import_tasks: tailscale.yml
#- import_tasks: val_tailscale.yml
#- import_tasks: deactivate_updates.yml
#- import_tasks: val_deupdates.yml
#- import_tasks: ipv6.yml
#- import_tasks: val_ipv6.yml
#- import_tasks: docker.yml
#- import_tasks: val_docker.yml
#- import_tasks: nodejs.yml
#- import_tasks: val_nodejs.yml
#- import_tasks: node_exporter.yml
#- import_tasks: val_node_exporter.yml
#- import_tasks: newrelic.yml
#- import_tasks: val_newrelic.yml
#- import_tasks: zsh.yml
#- import_tasks: val_zsh.yml
#- import_tasks: coolify.yml
#- import_tasks: val_coolify.yml
#- import_tasks: git.yml
#- import_tasks: val_git.yml